Uhf 4464 poc
City-of-Helsinki/drupal-helfi-platform-config pull request #297
Opened 2022-04-04 20:29 UTC by jeremysteerio

# [TASKNAME [UHF-0000](https://helsinkisolutionoffice.atlassian.net/browse/UHF-0000)](https://helsinkisolutionoffice.atlassian.net/browse/UHF-4464)
This branch contains code for both the subtasks of the issue.

## What was done
- Add new paragraph type _events_.  Make it addable to content fields on landing page and basic page types.
- Add classes to retrieve data from LinkedEvents API based on the given tapahtumat.hel.fi url
- Add basic JS functionality to query events based on the url and form a simple list from them

## How to install
- Checkout to branch. `make shell` into the container and run `drush en helfi_events -y`. 

## How to test
- Add a new landing page / basic page or edit an existing one. You should be able to add a paragraph of type events to to `field_content` (landing page and basic page) or to `field_lower_content` (basic page only).
- Add a new events-paragraph. Get the url for `field_api_url` by searching something from https://tapahtumat.hel.fi/fi/home and copying the url from the address bar.
- Viewing the page, you should see a matching list of events on the page that you saw at tapahtumat.hel.fi

2022-04-05 07:59 UTC, ltpk approved these changes
Code looks 🆗

2022-04-07 03:55 UTC, tuutti requested changes

2022-04-07 03:55 UTC, tuutti commented on helfi_features/helfi_events/src/Enum/CategoryKeywords.php
> +
Missing `declare(strict_types = 1);`

2022-04-07 03:55 UTC, tuutti commented on helfi_features/helfi_events/src/Enum/CategoryKeywords.php
> +  const CULTURE = [
Missing constant visibility (`public`)

2022-04-07 03:55 UTC, tuutti commented on helfi_features/helfi_events/src/Enum/CategoryKeywords.php
> +  const MOVIE = [
Missing constant visibility (`public`)

2022-04-07 03:55 UTC, tuutti commented on helfi_features/helfi_events/src/Enum/CategoryKeywords.php
> +  const INFLUENCE = [
Missing constant visibility (`public`)

2022-04-07 03:55 UTC, tuutti commented on helfi_features/helfi_events/src/Enum/CategoryKeywords.php
> +  const MUSEUM = [
Missing constant visibility (`public`)

2022-04-07 03:55 UTC, tuutti commented on helfi_features/helfi_events/src/Enum/CategoryKeywords.php
> +  const SPORT = [
Missing constant visibility (`public`)

2022-04-07 03:55 UTC, tuutti commented on helfi_features/helfi_events/src/Enum/CategoryKeywords.php
> +  const CAMPS = [
Missing constant visibility (`public`)

2022-04-07 03:55 UTC, tuutti commented on helfi_features/helfi_events/src/Enum/CategoryKeywords.php
> +  const TRIPS = [
Missing constant visibility (`public`)

2022-04-07 03:55 UTC, tuutti commented on helfi_features/helfi_events/src/Enum/CategoryKeywords.php
> +  const WORKSHOPS = [
Missing constant visibility (`public`)

2022-04-07 03:55 UTC, tuutti commented on helfi_features/helfi_events/src/Enum/CategoryKeywords.php
> +  const MUSIC = [
Missing constant visibility (`public`)

2022-04-07 03:55 UTC, tuutti commented on helfi_features/helfi_events/src/Enum/CategoryKeywords.php
> +  const FOOD = [
Missing constant visibility (`public`)

2022-04-07 03:55 UTC, tuutti commented on helfi_features/helfi_events/src/Enum/CategoryKeywords.php
> +  const DANCE = [
Missing constant visibility (`public`)

2022-04-07 03:55 UTC, tuutti commented on helfi_features/helfi_events/src/Enum/CategoryKeywords.php
> +  const THEATRE = [
Missing constant visibility (`public`)

2022-04-07 03:55 UTC, tuutti commented on helfi_features/helfi_events/src/Enum/CategoryKeywords.php
> +  const CHILDREN = 'yso:p4354';
Missing constant visibility (`public`)

2022-04-07 03:55 UTC, tuutti commented on helfi_features/helfi_events/src/EventsApiBase.php
> +
Missing `declare(strict_types = 1);`

2022-04-07 03:55 UTC, tuutti commented on helfi_features/helfi_events/src/EventsApiBase.php
> +  public function __construct(ClientInterface $httpClient, CacheBackendInterface $dataCache) {
These can be replaced to use constructor parameter promotion since we're using 8.0+ only: https://stitcher.io/blog/constructor-promotion-in-php-8

2022-04-07 03:55 UTC, tuutti commented on helfi_features/helfi_events/src/EventsApiBase.php
> +  protected function getFromCache(string $id) {
Missing return type

2022-04-07 03:55 UTC, tuutti commented on helfi_features/helfi_events/src/EventsApiBase.php
> +  public function parseParams($url) : array {
Missing type declaration for `$url`

2022-04-07 03:55 UTC, tuutti commented on helfi_features/helfi_events/src/LinkedEvents.php
> +
Missing `declare(strict_types = 1);`

2022-04-07 03:55 UTC, tuutti commented on helfi_features/helfi_events/src/LinkedEvents.php
> +  const API_URL = 'https://api.hel.fi/linkedevents/v1/';
Missing visibility

2022-04-07 03:55 UTC, tuutti commented on helfi_features/helfi_events/src/LinkedEvents.php
> +  public function getEventsRequest(array $options = []) {
Missing return type

2022-04-07 03:55 UTC, tuutti commented on helfi_features/helfi_events/src/EventsApiBase.php
> +      switch ($category) {
This whole switch block can be replaced with simple `match()`  expression to reduce code duplication:

```php
$keywords = [];

foreach (explode(',', $categories) as $category) {
  $map = match ($category) {
    default => CategoryKeywords::MOVIE,
    'movie' => CategoryKeywords::MOVIE,
    'sport' => CategoryKeywords::SPORT,
    'nature' => CategoryKeywords::CAMPS,
    'museum' => CategoryKeywords::MUSEUM,
   // etc....
  };
  $keywords = array_merge($map, $keywords);
}

return implode(',', $keywords);
```

2022-04-11 21:15 UTC, merged