UHF-5341: deleting non-helsinki TPR units
City-of-Helsinki/drupal-helfi-platform-config pull request #311
Opened 2022-04-25 08:37 UTC by ltpk

2022-04-25 09:51 UTC, jeremysteerio approved these changes
Works as described (unit count dropped to 28k from 46k).

2022-04-25 11:50 UTC, tuutti requested changes

2022-04-25 11:50 UTC, tuutti commented on src/Commands/RemoveNonHelsinkiTPRUnitsCommands.php
> +  public function __construct(EntityTypeManagerInterface $entity_type_manager) {
Use constructor property promotion: https://stitcher.io/blog/constructor-promotion-in-php-8

2022-04-25 11:50 UTC, tuutti commented on src/Commands/RemoveNonHelsinkiTPRUnitsCommands.php
> +    \Drupal::messenger()->addMessage($unit_count . ' units deleted.');
Use `$this->output()->writeln()`.

2022-04-25 11:50 UTC, tuutti commented on src/Commands/RemoveNonHelsinkiTPRUnitsCommands.php
> +      \Drupal::messenger()->addMessage('Deleting "' . $unit->label() . '"');
Use `$this->output()->writeln()`.

2022-04-25 11:50 UTC, tuutti commented on src/Commands/RemoveNonHelsinkiTPRUnitsCommands.php
> +      if ($lock_service->fetchLock($unit->id(), $unit->language()->getId(), NULL, 'tpr_unit')) {
Use named arguments here to skip optional/default paramers (https://www.php.net/manual/en/functions.arguments.php#functions.named-arguments):
`$lock_service->fetchLock($unit->id(), $unit->language()->getId(), entity_type: 'tpr_unit')`

2022-04-25 11:50 UTC, tuutti commented on src/Commands/RemoveNonHelsinkiTPRUnitsCommands.php
> +        $lock_service->release($unit->id(), $unit->language()->getId(), NULL, NULL, 'tpr_unit');
Use named arguments here to skip optional/default paramers (https://www.php.net/manual/en/functions.arguments.php#functions.named-arguments):
`$lock_service->release($unit->id(), $unit->language()->getId(), entity_type: 'tpr_unit')`

2022-04-25 11:51 UTC, tuutti requested changes

2022-04-25 11:51 UTC, tuutti commented on src/Commands/RemoveNonHelsinkiTPRUnitsCommands.php
> +    $lock_service = \Drupal::service('content_lock');
Inject `content_lock` service via drush.services.yml/constructor

2022-04-26 08:35 UTC, tuutti approved these changes

2022-04-26 08:37 UTC, tuutti requested changes
Nevermind. I think we need to add update hook that enables `content_lock` module since it's not done automatically.

2022-04-26 08:43 UTC, tuutti approved these changes

2022-04-26 08:47 UTC, merged