UHF-5699: Move event link inside title
City-of-Helsinki/drupal-helfi-platform-config pull request #328
Opened 2022-06-10 08:49 UTC by jeremysteerio

# [UHF-5699: Events paragraph accessibility fix](https://helsinkisolutionoffice.atlassian.net/browse/UHF-5699)
Event link is used as a container, which messes with screen readers. Move it inside title element,

## What was done
* Moved a-element inside title
* Made style changes to HDBT project to make the whole element clickable

## How to install
* In an instance of your choice, run `composer require drupal/helfi_platform_config:dev-UHF-5699-events-accessibility-fix drupal/hdbt:dev-UHF-5699-events-accessibility-fix`
* Clear cache `drush cr`

## How to test
* Edit or create either a landing- or standard page. Add a paragraph of type `Events`. Fill the fields.
* View the page. Link to the event should be located inside the event title, but the whole event item should be clickable.

## Other PRs
*

2022-06-10 12:05 UTC, Arkkimaagi requested changes
Looks and works quite good, some minor pointers about cleaning up the code.

2022-06-10 12:05 UTC, Arkkimaagi commented on helfi_features/helfi_events/assets/js/eventList.js
> +                <div class="event-list__tags event-list__tags--desktop role="Region" aria-label="${eventKeywords}">
* Missing a `"`-mark at the end of `class="` this is causing some problems with `role="Region"`
* `role="Region"` Why the capitalisation?

2022-06-10 12:05 UTC, Arkkimaagi commented on helfi_features/helfi_events/assets/js/eventList.js
> +              <div class="event-list__tags event-list__tags--mobile" role="Region" aria-label="${eventKeywords}">
What's up with the `role="Region"` capitalisation?

2022-06-10 12:05 UTC, Arkkimaagi commented on helfi_features/helfi_events/assets/js/eventList.js
> +                <div class="event__date">
This div is totally unused? There was no matching css style for it?

2022-06-10 12:05 UTC, Arkkimaagi commented on helfi_features/helfi_events/assets/js/eventList.js
> +                <div class="event__location"></div>
This div is not used for styling, why is it there?

2022-06-10 12:05 UTC, Arkkimaagi commented on helfi_features/helfi_events/assets/js/eventList.js
> +            <div class="event-list__image-container">
btw, do we get the photographer data from API? If we do, we could add it to the img-element as `data-photographer="John Smith"`

2022-06-13 10:09 UTC, lonkaanna approved these changes
Looks good in my opinion and Mikkos comments seem to be fixed!

2022-06-14 05:59 UTC, Arkkimaagi commented on helfi_features/helfi_events/assets/js/eventList.js
> +                  <span class="event-list__event-link-indicator"></span>
Lets check this out together

2022-06-14 07:40 UTC, Arkkimaagi commented on helfi_features/helfi_events/assets/js/eventList.js
> +                  <span class="event-list__event-link-indicator"></span>
flex:0 trick might help in future, but this is ok now.

2022-06-14 07:40 UTC, Arkkimaagi approved these changes

2022-06-14 07:59 UTC, merged