UHF-9158: language switcher titles visible for unpublished translations
City-of-Helsinki/drupal-helfi-platform-config pull request #626
Opened 2023-10-26 10:27 UTC by rpnykanen

# [UHF-9158](https://helsinkisolutionoffice.atlassian.net/browse/UHF-9158)

As anonymous user, language switcher would hide a language's title if the node has translation but translation is unpublished.

## What was done
Added language switcher alter which changes the url to another one and sets it disabled. 
- This way the language title will be visible. 
- A disabled switcher link is rendered as span and has no url mentioned in it.

## How to install
* Make sure your instance is up and running on latest dev branch.
    * `git pull origin dev`
    * `make fresh`
* Update the Helfi Platform config
    * `composer require drupal/helfi_platform_config:dev-UHF-9158`
* Run `make drush-updb drush-cr`

## How to test

etusivu, kasko groups, any other site preferably. As logged in user and anonymous...

* [ ] Check that this feature works
* [ ] Check that code follows our standards

2023-10-27 05:11 UTC, tuutti requested changes

2023-10-27 05:11 UTC, tuutti commented on helfi_platform_config.module
> +function helfi_platform_config_language_switch_links_alter(array &$links) {
Missing return type.

2023-10-27 05:11 UTC, tuutti commented on helfi_platform_config.module
> +  if (!$entity) {
$entity->isTranslatable() check can be moved here

2023-10-27 08:16 UTC, tuutti commented on tests/src/Functional/LanguageSwitcherAlterTest.php
> +    $this->drupalLogout();
I don't think this is necessary since we shouldn't be logged-in.

2023-10-30 13:47 UTC, dire approved these changes
Worked nicely!

2023-10-31 06:48 UTC, tuutti approved these changes

2023-10-31 07:14 UTC, merged