UHF-9534
City-of-Helsinki/drupal-helfi-platform-config pull request #675
Opened 2024-01-11 14:18 UTC by rpnykanen

# [UHF-9534](https://helsinkisolutionoffice.atlassian.net/browse/UHF-9534)
Saving a paragraphs supporting a design with or without a media causes error in some cases. 

## What was done
Remove media from paragraph on save if paragraph's design doesn't support media

**How to reproduce before applying the fix, with hero and list of links paragraph:**
- Create new content and add a hero or list of links paragraph.
  - Select a design with image and add the image. Save the content.
- Edit the content you just created. Change the design to `without image` and save the content.
- Go to media library and remove the media which you previously added to the paragraph
- Go back to edit the content and save it. You should see an error on the page.

## How to install
* Make sure your instance is up and running on latest dev branch.
    * `git pull origin dev`
    * `make fresh`
* Update the Helfi Platform config
    * `composer require drupal/helfi_platform_config:dev-UHF-9534`
* Run `make drush-updb drush-cr`

Test with `hero` and `list of links` paragraphs.
- Follow the reproduction steps ^.
- After deleting the media from media library, you should be able save the content with `design without image` successfully.

2024-01-12 06:24 UTC, tuutti requested changes

2024-01-12 06:24 UTC, tuutti commented on modules/helfi_paragraphs_hero/src/Entity/Hero.php
> +<?php
Missing `declare(strict_types = 1);`

2024-01-12 06:39 UTC, tuutti approved these changes

2024-01-12 13:29 UTC, hyrsky requested changes

2024-01-12 13:29 UTC, hyrsky commented on modules/helfi_paragraphs_list_of_links/src/Entity/ListOfLinksItem.php
>      return $this->getParentEntity()
`getParentEntity()` does not work correctly in `preSave()`. The parent is loaded from the database so the entity does not have the new value if it is edited.

See: https://git.drupalcode.org/project/paragraphs/-/blob/8.x-1.x/src/Entity/Paragraph.php?ref_type=heads#L128

2024-01-17 08:01 UTC, hyrsky approved these changes

2024-01-18 06:40 UTC, merged