Uhf 10259 curated event list
City-of-Helsinki/drupal-helfi-platform-config pull request #830
Opened 2024-10-18 14:25 UTC by jeremysteerio

# [UHF-10259](https://helsinkisolutionoffice.atlassian.net/browse/UHF-10259)
Add backend files for curated event list paragraph.

## What was done
- Add new paragraph: curated_event_list
- Add new external entity for Linked Events events
- Add new storageclient for retrieving events
- Add custom constraint and validator
- Add translations

## How to install

Install this branch:
* `composer require drupal/helfi_platform_config:dev-UHF-10259-curated-event-list`
* Run `drush updb -y`. This should install the new paragraph module.
* Run `drush cr`

Install the HDBT branch:
* `composer require drupal/hdbt:dev-UHF-10259-curated-event-list`
* Run `drush cr`

Import translations:
* Run `drush locale:check && drush locale:update`
* Run `drush cr`

## How to test

**Known issues / deviations from the sketch**
*  Link icon within the event title/link is the one we usually use. Discussion about this / possible jira ticket upcoming
* Time is displayed in the format we use, `d.m.Y H:i` and JS locale string format as in sketch. Confirming with design / writing a ticket about this as well.

Event testing:
* Add a new landing page. You should see curated event list option in the list for available paragraph types for _content_ field.
* Add events to the paragraph. You may do this by searching a name and letting autocompletion find the for you. You may also search event by ID. See field instructions for more info.
* View the page. The paragraph layout should match the sketch.

Try you some event combinations. These restrictions should apply:
* You can't add and event that is past its end time
* Only the top 3 events should be displayed, based on how you order them in the admin
* This is hard to test, but once an added event is past its end time, it should be hidden in the view

Also:
* View all -link should work with default settings. You should be able to change the link text and href.
* Check that code quality matches our standards.

## Continuous documentation

* [ ] This feature has been documented/the documentation has been updated
* [ ] This change doesn't require updates to the documentation

## Translations

* [x] Translations have been added to .po -files and included in this PR

## Other PRs

* Link to other PR

2024-10-21 15:19 UTC, teroelonen commented
Functionality works nicely, needs someone with more backend expertise to review the code.

2024-10-22 05:45 UTC, rpnykanen requested changes

2024-10-22 05:45 UTC, rpnykanen commented on modules/helfi_paragraphs_curated_event_list/helfi_paragraphs_curated_event_list.module
> +  if (
Turn the condition around and return early to prevent nesting

2024-10-22 05:45 UTC, rpnykanen commented on modules/helfi_paragraphs_curated_event_list/src/Plugin/Validation/Constraint/CuratedEventConstraintValidator.php
> +    // Early return if no events are selected.
unnecessary comment

2024-10-22 05:45 UTC, rpnykanen commented on modules/helfi_paragraphs_curated_event_list/helfi_paragraphs_curated_event_list.module
> +      $build[$has_ended ? 'past_events' : 'future_or_ongoing'][] = Drupal::entityTypeManager()
This kind of logic and constants could be neatly hidden in a bundle class

2024-10-22 08:56 UTC, merged