UHF-10239: Adds image gallery paragraph
City-of-Helsinki/drupal-helfi-platform-config pull request #840
Opened 2024-11-07 08:40 UTC by annadruid

# [UHF-10239](https://helsinkisolutionoffice.atlassian.net/browse/UHF-10239)

## What was done

* This thing was fixed

## How to install
* Make sure your instance is up and running on latest dev branch.
    * `git pull origin dev`
    * `make fresh`
* Update the Helfi Platform config
    * `composer require drupal/helfi_platform_config:dev-UHF-10239 `
* Run `make drush-updb drush-cr`

## How to test

* [ ] Check that this feature works
* [ ] Check that code follows our standards

## Continuous documentation

* [ ] This feature has been documented/the documentation has been updated
* [ ] This change doesn't require updates to the documentation

## Translations

* [ ] Translations have been added to .po -files and included in this PR

## Other PRs

* Link to other PR

2024-11-15 06:51 UTC, tuutti requested changes

2024-11-15 07:25 UTC, annadruid commented on modules/hdbt_admin_tools/src/Plugin/Validation/Constraint/ImageGalleryConstraint.php
> +
Fixed!

2024-11-15 07:25 UTC, annadruid commented on modules/hdbt_admin_tools/src/Plugin/Validation/Constraint/ImageGalleryConstraintValidator.php
> +<?php
Fixed!

2024-11-15 07:26 UTC, annadruid commented on modules/hdbt_admin_tools/src/Plugin/Validation/Constraint/ImageGalleryConstraintValidator.php
> +  public function validate(mixed $value, Constraint $constraint) {
Fixed!

2024-11-15 08:37 UTC, tuutti approved these changes

2024-11-15 15:08 UTC, teroelonen requested changes
Pending the image style changes that I wrote to you on chat. Otherwise looks very good to me!

2024-11-18 05:40 UTC, annadruid commented
> Pending the image style changes that I wrote to you on chat. Otherwise looks very good to me!

The image styles have now been updated!

2024-11-18 13:04 UTC, teroelonen approved these changes
Really great work with this one! 🦖

2024-11-18 15:26 UTC, merged